sensor:
  - name: "Light Schedule Master"
    unique_id: light_schedule_master
    # We removed the delay_off here because the Lutron handles the 5 mins
    state: >-
      {% set lead = label_entities('light_schedule') 
        | expand
        | sort(attribute='last_changed', reverse=true ) 
        | map(attribute='entity_id') 
        | first
      %}
      {{ lead }}|{{ as_timestamp(states[lead].last_changed) }}|{{ states[lead].state }}
